### ISSUE TITLE
comparison to GridNet

### ISSUE THREAD

**Issue by stubborn-dwarf** [juntang-zhuang/ShelfNet#4]
How come you didn't compare to [Residual Conv-Deconv Grid Network for Semantic Segmentation](https://arxiv.org/abs/1707.07958)? They proposed a multi-path network for semantic segmentation a while ago, which you claim as your main contribution.

**Comment by juntang-zhuang** [comment]
Thanks for your comment and interest in our work. We will cite their paper on GridNet and comment on the differences in our report, we are so sorry not to find their great work before publishing our report. But there are several points we want to clarify: 

First, we propose ShelfNet independently, which is not a copy of GridNet, because we have not read their paper until you comment here. That's also why we did not compare to it in the report. In fact, the idea of ShelfNet comes from another project on our github "LadderNet", it's an extension of LadderNet.

Second, the big-structure is different. (1) Columns of GridNet are arranged as (down, down,...) (up, up,...), but columns of ShelfNet are arranged as (down,up) (down,up) ...[By "down"("up") we refer to decrease (increase) of spatial size.] Each (down,up) module is like a U-Net or a SegNet or Link-Net. (2)This (down,up) design enables ShelfNet to have much deeper paths than GridNet. Please see the attachment for a detailed illustration with pictures.
![gridnet_shelfnet_comparison 001](https://user-images.githubusercontent.com/44451229/50406055-1d4e5700-078c-11e9-90e8-9a2288553e46.png)
 
Third, the detailed structure is different. (1) GridNet uses residual block, but here we use shared-weights residual block. 
(2) For the transition between rows, GridNet performs addition-deconv, while we use addition-(shared-weights residual block) - deconv.

Fourth, our contributions include the shelf-shaped structure, shared-weights residual block and the real-time inference speed. Although both GridNet and ShelfNet use multi-path ideas, this idea is actually very broad, the designs seem similar but are different. 

Finally, thanks for your helpful comment. This issue started because we did not read the GridNet paper until you told us. We will add comparison and revise our report. Thanks again and Merry Christmas.

**Comment by stubborn-dwarf** [comment]
Thank you for the comparison! It makes me happy to see that you are willing to revise your report, this is a truly courageous step and an example of good research. Please note that I am not affiliated with Fourure et al and am just a fan of multi-path networks. I just wanted to hear about your thoughts on GridNet since I would like this new type of neural networks that you and Fourure et al propose to flourish.
